[project]
name = "cli-error"
version = "0.1.1"
description = "Error handling and reporting utilities for CLI applications."
requires-python = ">=3.12"
dependencies = ["rich"]

[dependency-groups]
dev = [
    "mypy",
    "pytest>=9.1.1",
    "black",
    "isort",
    "flake8",
    "tox",
    "tox-uv",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cli_error"]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
