[tox]
env_list = typecheck, test, lint
requires =
    tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
with_dev = false

[testenv:test]
dependency_groups =
    test
commands =
    pytest {posargs}

[testenv:lint]
dependency_groups =
    lint
commands =
    black --check src/ tests/
    isort --check src/ tests/
    flake8 src/ tests/

[testenv:typecheck]
dependency_groups =
    typecheck
commands =
    mypy src/ tests/
